### ISSUE TITLE
Changing ownership?

### ISSUE THREAD

**Issue by BoboTiG** [zverev-iv/choco-httpie#1]
Hello @zverev-iv,

Thank you for having maintained the Chocolatey package! :)

I am the maintainer of HTTPie and would like to improve overall packaging (including Linux and macOS packages) and so I would like to check with you if you would be OK to move your repository at our own team level (@httpie)?
I would allow me to better control updates.

Maybe could we continue the discussion via email (`mickael AT apible DOT io`)?

Thanks a lot for your answer and work,

**Comment by jkbrzt** [comment]
@zverev-iv gentle bump 👋🏻

**Comment by zverev-iv** [comment]
Hello! I'm sorry to be late with the reply. It's Ok!
If you need any help with package code, feel free to contact me :)
And big thanks for creating httpie!

**Comment by BoboTiG** [comment]
No worries. Thanks to you for all what you've done :)
